### ISSUE TITLE
use @inputs instead

### ISSUE THREAD

**Issue by MatthewCroughan** [colemickens/nixos-flake-example#3]
https://github.com/kanashimia/nixos/blob/330206bf1d120174702f6e09423c1c19bc2ae847/flake.nix does this.

Instead of:
https://github.com/colemickens/nixos-flake-example/blob/daf9133c35ee2d2ec78e625b96fbd79dd39e6608/flake.nix#L10-L12

Would it not make more sense to just have this?

```
outputs = { config,lib, ... }@inputs: {
```

I do not understand the purpose of `let`ing those values. I know it says *ignoreme* but I can't! I feel I understand the rest of this example perfectly, but this part doesn't make sense.

At least a comment could be provided to suggest why these values are being let if `@input` does not suffice.

**Comment by colemickens** [comment]
No.

`{a, b, ...}@inputs` binds `a` and `b` to `inputs.a` and `inputs.b`. Unlike other flakes, I don't like this, and I like having to put/see `inputs.<input>` everywhere they're used.

The "ignoreme" part is entirely 100% unrelated to the function signature, it's just a simple extra variable being defined (`ignoreme`) that encompasses a nixos module that ensures the flake/non-flake version strings are identical. Lines 11 and 20 could be removed and the example would be practically the same (though without `ignoreme`) the flake/non-flake would produce different outputs due to different version strings).
